[package]
name = "notch"
version = "0.2.4"
description = "Notch - Dynamic-Island-artige Infoanzeige fuer Windows"
authors = ["Nojo"]
edition = "2021"

[lib]
name = "notch_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "protocol-asset"] }
tauri-plugin-opener = "2"
tauri-plugin-drag = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tiny_http = "0.12"
base64 = "0.22"
image = "0.25"
ureq = { version = "3", features = ["json"] }
webview2-com = "0.39"
tauri-plugin-global-shortcut = "2"
arboard = "3"
tauri-plugin-updater = "2"
rustfft = "6"
socket2 = { version = "0.5", features = ["all"] }
qrcode = { version = "0.14", default-features = false, features = ["svg"] }

[dependencies.windows]
version = "0.62"
features = [
  "Foundation",
  "Media_Control",
  "Storage_Streams",
  "Win32_Foundation",
  "Win32_UI_WindowsAndMessaging",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_System_Threading",
  "Win32_System_Com",
  "Win32_System_Com_StructuredStorage",
  "Win32_System_Variant",
  "Win32_Media_Audio",
  "Win32_Media_Audio_Endpoints",
  "Win32_Devices_FunctionDiscovery",
  "Win32_Devices_Properties",
  "Win32_UI_Shell_PropertiesSystem",
  "Win32_UI_Shell",
  "Win32_System_DataExchange",
  "Win32_System_Memory",
  "Win32_Security",
  "Win32_Security_Cryptography",
  "Win32_UI_Input_XboxController",
  "Win32_System_Registry",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
